# Generated by Django 5.0.2 on 2024-02-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_like_count_alter_author_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like_count',
        ),
    ]
