# Generated by Django 5.0.2 on 2024-02-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_categories_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
